apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dotnet
  labels:
    app: dotnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: test-dotnet:1.0.0
